###############################
#######    BestTools    #######
###############################

# BestTools lets you automatically use the best tool you have in your inventory
# when breaking blocks or attacking mobs. It also features automatic hotbar
# refill when you run out of blocks.


###############################
#######    Commands     #######
###############################

# /besttools (or /bt:)  Toggle BestTools per player
# /besttools hotbar:    Toggles whether BestTools only uses tools from your hotbar
# /besttools reload:    Reloads the config file

# /refill (or /rf:)     Toggle automatic hotbar refill per player

# /besttools bl                      Shows your blacklist
# /besttools bl add                  Adds your current item to your blacklist
# /besttools bl add <items...>       Adds all specified items to your blacklist
# /besttools bl add inventory        Adds all items in your inventory to your blacklist
# /besttools bl add hotbar           Adds all items in your hotbar to your blacklist
# /besttools bl remove               Removes your current item from your blacklist
# /besttools bl remove <items...>    Removes all specified items from your blacklist
# /besttools bl remove inventory     Removes all items in your inventory from your blacklist
# /besttools bl remove hotbar        Removes all items in your hotbar from your blacklist
# /besttools bl reset                Removes all items from your blacklist


###############################
#######   Permissions   #######
###############################

# besttools.use:        Allows to use the /besttools (or /bt) command
# besttools.refill:     Allows to use the /refill (or /rf) command
# besttools.reload:     Allows to use the /besttools reload command


###############################
#######  Placeholders   #######
###############################

# When using PlaceholderAPI, you can use the following placeholders:

# %besttools_btenabled%    - true if this player has BestTools enabled, otherwise false
# %besttools_rfenabled%    - true if this player has Refill enabled, otherwise false
# %besttools_hotbaronly%   - true if this player has set BestTools to hotbar-only
# %besttools_favoriteslot% - the slot number this player chose as favorite slot


###############################
####### General config  #######
###############################

# When false, new players have to run /besttools or /bt once to enable BestTools
besttools-enabled-by-default: false

# When false, new players have to run /refill or /rf once to enable hotbar refill
refill-enabled-by-default: false

# Only use tools from the hotbar? Can be changed per player using /besttools hotbar
hotbar-only: true

# The preferred slot where BestTools should move the tool if it's not in the hotbar
# and hotbar-only is set to false. Must be a number between 0 (leftmost hotbar slot)
# and 8 (rightmost hotbar slot)
# Set this to -1 to always use the player's current slot
favorite-slot: 8

# When set to false, /besttools and /refill will only work in survival game mode
# When set to true, it works in survival and adventure game mode
allow-in-adventure-mode: false

# When enabled, BestTools will not attempt to switch any tools when the player is
# holding a sword, crossbow, bow or trident
dont-switch-during-battle: true

# Don't use items if they are going to break with this usage
# NOT IMPLEMENTED YET
#prevent-item-break: true

# Allow /besttools to switch to your sword/axe (whatever is better) when attacking mobs?
use-sword-on-hostile-mobs: true

# Use axe instead of sword when the axe does more damage (it's slower though and does not deal sweep damage)
use-axe-as-sword: false

# NOT IMPLEMENTED YET, comes with next update
#use-sword-on-friendly-mobs: false
#use-sword-on-players: false

###############################
####### Global blacklist ######
###############################

# You can add blocks to the global blacklist here that will apply to ALL players.
# Blocks broken that are mentioned in this list will not trigger BestTools.

# Example:
#
# global-block-blacklist:
# - POTATOES
# - BEETROOTS
# - CARROTS
# - WHEAT

global-block-blacklist:

###############################
####### Update checker  #######
###############################

# Checks for updates (asynchronously).
# When enabled, a message is printed in the console if a new
# version has been found, and OPs will be notified when they join the server
# When set to true, check for updates on startup and every X hours (see "check-interval" below)
# When set to on-startup, only check on server startup
# When set to false, don't check for updates
check-for-updates: true

# When you set "check-for-updates" to true, you can define the amount
# of hours inbetween each update check.
check-interval: 4

###############################
#######  Localization   #######
###############################

# Available color codes:
# &0 Black        &6 Gold       &c Red
# &1 Dark Blue    &7 Gray       &d Light Purple
# &2 Dark Green   &8 Dark Gray  &e Yellow
# &3 Dark Aqua    &9 Blue       &f White
# &4 Dark Red     &a Green
# &5 Dark Purple  &b Aqua

# Available formatting codes:
# &k Obfuscated   &m Strikethrough
# &l Bold         &o Italic
# &n Underline    &r Reset

# Please note that using color codes in the GUI is not supported yet.

# You can set messages to an empty String ("") to avoid displaying those messages.

##### You can edit these messages yourself or uncomment the existing translations (see below)
message-besttools-enabled: "&7BestTools has been &aenabled&7."
message-besttools-disabled: "&7BestTools has been &cdisabled&7."
message-refill-enabled: "&7Refill has been &aenabled&7."
message-refill-disabled: "&7Refill has been &cdisabled&7."
message-besttools-usage: "&7Hint: Type &6/besttools&7 or &6/bt&7 to automatically use the best tool when breaking blocks."
message-refill-usage": "&7Hint: Type &6/refill&7 or &6/rf&7 to automatically refill empty items from your inventory."
message-hotbar-only-enabled: "&7BestTools will only use tools from your hotbar."
message-hotbar-only-disabled: "&7BestTools will use all tools from your inventory."
gui-favorite-slot: "Set as favorite slot"
gui-favorite-slot-lore: "If your hotbar is full and BestTools uses a tool from your inventory, it will be places in this slot."
gui-besttools-lore: "Automatically chooses the best tools when breaking blocks."
gui-hotbar-lore: "When enabled, BestTools will only use tools from your hotbar instead of from your whole inventory."
gui-refill-lore: "Automatically refills empty hotbar slots."

##### English
#message-besttools-enabled: "&7BestTools has been &aenabled&7."
#message-besttools-disabled: "&7BestTools has been &cdisabled&7."
#message-refill-enabled: "&7Refill has been &aenabled&7."
#message-refill-disabled: "&7Refill has been &cdisabled&7."
#message-besttools-usage: "&7Hint: Type &6/besttools&7 or &6/bt&7 to automatically use the best tool when breaking blocks."
#message-refill-usage": "&7Hint: Type &6/refill&7 or &6/rf&7 to automatically refill empty items from your inventory."
#message-hotbar-only-enabled: "&7BestTools will only use tools from your hotbar."
#message-hotbar-only-disabled: "&7BestTools will use all tools from your inventory."
#gui-favorite-slot: "Set as favorite slot"
#gui-favorite-slot-lore: "If your hotbar is full and BestTools uses a tool from your inventory, it will be places in this slot."
#gui-besttools-lore: "Automatically chooses the best tools when breaking blocks."
#gui-hotbar-lore: "When enabled, BestTools will only use tools from your hotbar instead of from your whole inventory."
#gui-refill-lore: "Automatically refills empty hotbar slots."

##### Chinese
#message-besttools-enabled: "&7自动切换最佳工具 &a已启用&7."
#message-besttools-disabled: "&7自动切换最佳工具 &c已禁用&7."
#message-refill-enabled: "&7自动填充方块 &a已启用&7."
#message-refill-disabled: "&7自动填充方块 &c已禁用&7."
#message-besttools-usage: "&7提示: 输入指令 &6/besttools&7 或 &6/bt&7 可以在破坏任意方块时自动切换至最佳工具."
#message-refill-usage: "&7提示: 输入指令 &6/refill&7 或 &6/rf&7 可以从背包里自动填充手中放置完的物品."
#message-hotbar-only-enabled: "&7自动切换最佳工具 仅会根据快捷栏切换工具."
#message-hotbar-only-disabled: "&7自动切换最佳工具 会根据背包内的所有物品切换工具."
#gui-favorite-slot: "设置你的想要工具栏位"
#gui-favorite-slot-lore: "如果你的快捷栏已满,自动工具系统会从你的背包中选取工具置于该工具栏位中"
#gui-besttools-lore: "在破坏方块时自动选择最佳工具."
#gui-hotbar-lore: "启用此项后, 插件只会选取你快捷栏中的最佳工具,而非整个背包内的最佳工具."
#gui-refill-lore: "在放置方块时自动选择最佳方块."

##### Chinese (Traditional)
#message-besttools-enabled: "&7自動切換最佳工具 &a已啟用&7."
#message-besttools-disabled: "&7自動切換最佳工具 &c已禁用&7."
#message-refill-enabled: "&7自動填充方塊 &a已啟用&7."
#message-refill-disabled: "&7自動填充方塊 &c已禁用&7."
#message-besttools-usage: "&7提示: 輸入指令 &6/besttools&7 或 &6/bt&7 可以在破壞任意方塊時自動切換至最佳工具."
#message-refill-usage: "&7提示: 輸入指令 &6/refill&7 或 &6/rf&7 可以從背包裡自動填充手中放置完的物品."
#message-hotbar-only-enabled: "&7自動切換最佳工具 僅會根據快捷欄切換工具."
#message-hotbar-only-disabled: "&7自動切換最佳工具 會根據背包內的所有物品切換工具."
#gui-favorite-slot: "Set as favorite slot"
#gui-favorite-slot-lore: "If your hotbar is full and BestTools uses a tool from your inventory, it will be places in this slot."
#gui-besttools-lore: "Automatically chooses the best tools when breaking blocks."
#gui-hotbar-lore: "When enabled, BestTools will only use tools from your hotbar instead of from your whole inventory."
#gui-refill-lore: "Automatically refills empty hotbar slots."

##### Dutch
#message-besttools-enabled: "&7BestTools is &aingeschakeld&7."
#message-besttools-disabled: "&7BestTools is &cuitgeschakeld&7."
#message-refill-enabled: "&7Hervullen is &aingeschakeld&7."
#message-refill-disabled: "&7Hervullen is &cuitgeschakeld&7."
#message-besttools-usage: "&7Hint: Type &6/besttools&7 of &6/bt&7 om automatisch het beste gereedschap te gebruiken om blokken te breken."
#message-refill-usage": "&7Hint: Type &6/refill&7 of &6/rf&7 om automatisch lege vakken te hervullen uit je inventaris."
#message-hotbar-only-enabled: "&7BestTools zal alleen gereedschap uit je hotbar gebruiken."
#message-hotbar-only-disabled: "&7BestTools zal alle gereedschappen uit je inventaris gebruiken."
#gui-favorite-slot: "Zet als favoriete vak"
#gui-favorite-slot-lore: "Als je hotbar vol is en BestTools een gereedschap gebruikt uit je inventaris, zal het in de juiste vak worden geplaatst."
#gui-besttools-lore: "Automatisch een het beste gereedschap kiezen tijdens het breken van blokken."
#gui-hotbar-lore: "Wanneer ingeschakeld, zal BestTools alleen gereedschap uit je hotbar gebruiken in plaats van je gehele inventaris."
#gui-refill-lore: "Hervult automatisch lege hotbar vakken."

##### German
#message-besttools-enabled: "&7BestTools wurde &aaktiviert&7."
#message-besttools-disabled: "&7BestTools wurde &cdeaktiviert&7."
#message-refill-enabled: "&7Refill wurde &aaktiviert&7."
#message-refill-disabled: "&7Refill wurde &cdeaktiviert&7."
#message-besttools-usage: "&Hinweis: Benutze &6/besttools&7 oder &6/bt&7 um die automatische Werkzeugauswahl zu aktivieren."
#message-refill-usage": "&7Hinweis: Benutze &6/refill&7 oder &6/rf&7 um die automatische Itemauffüllung zu aktivieren."
#message-hotbar-only-enabled: "&7BestTools wird nur Werkzeuge aus deiner Hotbar benutzen."
#message-hotbar-only-disabled: "&7BestTools wird alle Werkzeuge aus deinem Inventar benutzen."
#gui-favorite-slot: "Als Lieblingsslot festlegen"
#gui-favorite-slot-lore: "Wenn deine Hotbar voll ist und BestTools ein Werkzeug aus deinem Inventar nimmt, wird es in diesem Slot platziert."
#gui-besttools-lore: "Benutzt automatisch das beste Werkzeuge beim Abbauen von Blöcken."
#gui-hotbar-lore: "Wenn aktiviert wird BestTools nur Werkzeuge aus deiner Hotbar benutzen."
#gui-refill-lore: "Füllt automatisch leere Hotbar-Slots auf."

##### Polish
#message-besttools-enabled: "&7BestTools zostało &awłączone&7."
#message-besttools-disabled: "&7BestTools zostało &cwyłączone&7."
#message-refill-enabled: "&7Auto-refill został &awłączony&7."
#message-refill-disabled: "&7Auto-refill został &cwyłączony&7."
#message-besttools-usage: "&7Podpowiedź: Wpisz &6/besttools&7 lub &6/bt&7 by automatycznie użyć naodpowiedniejszych narzędzi do niszczenia danego typu bloków."
#message-refill-usage": "&7Podpowiedź: Wpisz &6/refill&7 lub &6/rf&7 by automatycznie wypełnić pasek szybkiego wyboru przedmiotami z ekwipunku."
#message-hotbar-only-enabled: "&7BestTools będzie używać tylko narzędzi z paska szybkiego wyboru."
#message-hotbar-only-disabled: "&7BestTools będzie używać wszystkich narzędzi z ekwipunku."
#gui-favorite-slot: "Ustaw ten slot jako ulubiony"
#gui-favorite-slot-lore: "Jeśli twój pasek szybkiego wyboru jest pełen, a BestTools używa narzędzia z twojego ekwipunku, będzie ono automatycznie umieszczone w tym slocie."
#gui-besttools-lore: "Automatycznie używa najodpowiedniejszego narzędzia do niszczenia danego typu bloków."
#gui-hotbar-lore: "Gdy włączony, BestTools użyje tylko narzędzia z paska szybkiego wyboru zamiast z całego ekwipunku."
#gui-refill-lore: "Automatycznie wypełnia puste sloty paska szybkiego wyboru."

##### Russian
#message-besttools-enabled: "&7BestTools &aактивирован&7."
#message-besttools-disabled: "&7BestTools &cдеактивирован&7."
#message-refill-enabled: "&7Заполнение &aактивировано&7."
#message-refill-disabled: "&7Заполнение &cдеактивировано&7."
#message-besttools-usage: "&7Подсказка: Введите &6/besttools&7 или &6/bt&7 чтобы автоматически использовать лучший предмет для ломания блоков."
#message-refill-usage": "&7Подсказка: Введите &6/refill&7 или &6/rf&7 чтобы автоматически наполнять ваши предметы в инвентаре."
#message-hotbar-only-enabled: "&7BestTools будет использовать только инструменты с вашей панели быстрого доступа."
#message-hotbar-only-disabled: "&7BestTools будет использовать все инструменты из вашего инвентаря."
#gui-favorite-slot: "Установить любимый слот"
#gui-favorite-slot-lore: "Если ваша панель быстрого доступа заполнена и BestTools использует инструмент из вашего инвентаря, он будет размещен в этом слоте."
#gui-besttools-lore: "Автоматически выбирает лучшие инструменты при ломании блоков."
#gui-hotbar-lore: "Когда этот параметр включен, BestTools будет использовать инструменты только из вашей панели быстрого доступа, а не из всего вашего инвентаря."
#gui-refill-lore: "Автоматически заполняет пустые слоты панели быстрого доступа."

##### Spanish
#message-besttools-enabled: "&7Has &aactivado &7la selección automática de herramientas."
#message-besttools-disabled: "&7Has &cdesactivado &7la selección automática de herramientas."
#message-refill-enabled: "&7Has &aactivado &7la reposición automática de objetos."
#message-refill-disabled: "&7Has &cdesactivado &7la reposición automática de objetos."
#message-besttools-usage: "&7Usa el comando &6/besttools &7para cambiar automáticamente la herramienta que mejor convenga para cada situación."
#message-refill-usage": "&7Usa el comando &6/refill &7para reponer automáticamente los bloques de tu inventario."
#message-hotbar-only-enabled: "&7Ahora solo se seleccionarán automáticamente las herramientas alojadas en tu cinturón."
#message-hotbar-only-disabled: "&7Ahora se seleccionarán automáticamente las herramientas de tu inventario y tu cinturón."
#gui-favorite-slot: "&7Determina la ranura que quieres utilizar de tu cinturón."
#gui-favorite-slot-lore: "&7Si tu cinturón está lleno, la selección automática de herramientas, moverá la herramienta desde tu inventario hasta esta ranura."
#gui-besttools-lore: "&7Selecciona automáticamente la mejor herramienta para romper bloques."
#gui-hotbar-lore: "&7Cuando está activado, la selección automática de herramientas solo utilizará las herramientas de tu cinturón vez de las existentes en tu inventario."
#gui-refill-lore: "&7Rellena automáticamente las ranuras del cinturón."

##### Turkish
#message-besttools-enabled: "&7BestTools &aaktif edildi&7."
#message-besttools-disabled: "&7BestTools &cdeaktif edildi&7."
#message-refill-enabled: "&7Otomatik doldurma &aaktif edildi&7."
#message-refill-disabled: "&7Otomatik doldurma &cdeaktif edildi&7."
#message-besttools-usage: "&7İpucu: Blok kırarken otomatik olarak en iyi aleti kullanmak için &6/besttols&7 veya &6/bt&7 yazınız."
#message-refill-usage": "&7İpucu: Slotunuzdaki blokları otomatik doldurmak için &6/refill&7 veya &6/rf&7 yazınız."
#message-hotbar-only-enabled: "&7BestTools sadece slotlarınızdaki aletleri kullanacaktır."
#message-hotbar-only-disabled: "&7BestTools envanterinizdeki bütün aletleri kullanacaktır."
#gui-favorite-slot: "Favori slot olarak seç"
#gui-favorite-slot-lore: "Eğer seçmiş olduğunuz slot zaten doluysa ve BestTools envanterinizdeki bir aleti kullanıyorsa, alet otomatik olarak bu slota yerleştirilecektir."
#gui-besttools-lore: "Blok kırarken otomatik olarak en iyi aleti seçer."
#gui-hotbar-lore: "Aktifken, BestTools envanterinizdeki öğeler yerine sadece slotlarınızdaki aletleri kullanır."
#gui-refill-lore: "Otomatik olarak boş slotlarınızı doldurur."

############################
##### Technical stuff! #####
############################

# Show some infos on startup
verbose: true

# You can enable debug mode using /bt debug (permission: besttools.debug)
debug: false

# Prints the Material<>Tool map to a csv file
dump: false

# You can enable performance test using /bt performance (permission: besttools.debug)
measure-performance: false

# Do you like bad puns?
puns: false

# Do not change the following line! It is used to automatically update
# your config to the latest version. Your changes will be kept.
config-version: 17
